### ISSUE TITLE
save ggvis plots as PNGs for LaTeX

### ISSUE THREAD

**Issue by barryrowlingson** [yihui/knitr#906]
ggvis plots can be written to PNG (or SVG) files using `export_png` - this is a bit of a tricky setup since it needs the `vega` module for `node.js` and a path to a `vg2png` binary, but once that's done it seems to just work (at least for simple examples).

Example: http://stackoverflow.com/questions/27193287/using-ggvis-in-rnw-with-knitr/27193693#27193693

In LaTeX you can call `export_png` and then have an `\includegraphics` line, but it would be cool to have it done seamlessly when a `ggvis` object is printed, including all the LaTeX figure stuff.

I did have a quick play at hooking into the print method for ggvis but no joy - browser kept displaying the original!

**Comment by Wario84** [comment]
Hi guys, I'm struggling a lot trying to set up the export_png(), I have tried both in windows and Linux without success... 
In Windows:
```
library(ggvis) 
mtcars %>% ggvis(~hp, ~mpg, fill=~factor(cyl)) %>% layer_smooths() %>% export_png()
```
The outcome is this 

```
Writing to file plot.png
undefined:3
return x["data"]["domain"];
                ^

TypeError: Cannot read property 'domain' of undefined
    at eval [as get] (eval at <anonymous> (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\node_modules\datalib\src\util.js:147:20), <anonymous>:3:17)
    at eval [as add] (eval at create (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\node_modules\datalib\src\aggregate\measures.js:175:23), <anonymous>:3:14)
    at Facetor.proto._add (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\node_modules\datalib\src\aggregate\aggregator.js:158:31)
    at add (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\src\transforms\Aggregate.js:174:31)
    at Array.forEach (native)
    at Aggregate.prototype.transform (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\src\transforms\Aggregate.js:190:13)
    at Aggregate.prototype.evaluate (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\src\transforms\Transform.js:48:15)
    at Node.dataRef (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\src\scene\Scale.js:387:15)
    at Node.domainMinMax (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\src\scene\Scale.js:429:15)
    at Node.quantitative (C:\Users\mglez\AppData\Roaming\npm\node_modules\vega\src\scene\Scale.js:223:18)
Warning message:
running command '"C:\Users\mglez\AppData\Roaming\npm\vg2png.cmd" C:\Users\mglez\AppData\Local\Temp\RtmpSWJcGx\ggvis25e828cd4fe4/plot.json plot.png' had status 1 

```
And my session info:

```
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggvis_0.4.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5     XML_3.98-1.4    digest_0.6.9    dplyr_0.4.3     assertthat_0.1  mime_0.4        bitops_1.0-6    R6_2.1.2        jsonlite_0.9.22 xtable_1.8-2   
[11] DBI_0.4-1       magrittr_1.5    lazyeval_0.2.0  RJSONIO_1.3-0   tools_3.3.0     RSelenium_1.3.5 RCurl_1.95-4.8  shiny_0.13.2    httpuv_1.3.3    parallel_3.3.0 
[21] caTools_1.17.1  htmltools_0.3.5
```

Any ideas how to solve this?

Thanks a lot,

**Comment by yihui** [comment]
@Wario84 I don't think this question is relevant to knitr. Please post it to the ggvis repository instead.

**Comment by Wario84** [comment]
Dear @yihui , is just that my final objective is to insert a ggvis object as a picture using knitr, so maybe there is an alternative way, for instance knit_print.ggvis() ?

**Comment by yihui** [comment]
I mean the error message came from ggvis instead of knitr, so that has to be fixed on the ggvis side before I can take a look. ggvis should already have a knit_print.ggvis method.
